## PROUNI Data Processing

Start by importing the frameworks

In [1]:
import sys
sys.path.append("../")
import pandas as pd
import src.util.file as file
import src.prouni.prouni as prouni
import src.data.data as dt
pd.set_option('display.float_format',lambda x: '%.0f' % x)

***

## Start by importing the different tables

In [2]:
dados_ies = file.load(file_path='../data/raw/dados_ies.csv',sep=',')

dados_ies

,id_ies,nome,tipo_instituicao,rede,situacao_funcionamento,id_municipio,sigla_uf
0,1540,Instituto De Ensino Superior De Rondônia,Privada,Privada,Ativa,1100023,RO
1,4613,Centro Universitário Faema,Privada,Privada,Ativa,1100023,RO
2,10929,Faculdade Santo Andre,Privada,Privada,Ativa,1100049,RO
3,1209,Faculdade De Administracao De Empresas De Cacoal,Privada,Privada,Ativa,1100049,RO
4,1861,Faculdade De Direito De Cacoal,Privada,Privada,Ativa,1100049,RO
...,...,...,...,...,...,...,...
6584,4520,Faculdade Cenacap,Privada,Privada,Inativa,5300108,DF
6585,5284,Faculdade Para O Ensino Das Ciencias Juridicas...,Privada,Privada,Inativa,5300108,DF
6586,4923,Instituto Saber,Privada,Privada,Inativa,5300108,DF
6587,5030,Faculdade De Filosofia E Ciencias Do Planalto ...,Privada,Privada,Inativa,5300108,DF
6588,5042,Seminario Nacional Itej,Privada,Privada,Inativa,5300108,DF

In [3]:
dados_prouni = file.load(file_path='../data/raw/dados_prouni.csv',sep=',',encoding='latin1')
dados_prouni

,ano,sigla_uf,id_municipio,cpf,sexo,raca_cor,data_nascimento,beneficiario_deficiente,id_ies,campus,nome_municipio_ies,curso,turno_curso,tipo_bolsa,modalidade_ensino
0,2015,AP,1600303,***024922**,2,5,1966-11-12,0,1491,NaN,NaN,GEOGRAFIA,5,2,2
1,2015,AP,1600303,***978542**,2,4,1982-01-25,0,1491,NaN,NaN,PEDAGOGIA,5,1,2
2,2015,AP,1600303,***678932**,2,4,1970-04-09,0,322,NaN,NaN,GESTAO DA TECNOLOGIA DA INFORMACAO,5,1,2
3,2015,AP,1600303,***406412**,2,2,1993-05-31,0,322,NaN,NaN,ADMINISTRACAO,5,1,2
4,2015,AP,1600303,***867472**,2,4,1979-05-03,0,322,NaN,NaN,ADMINISTRACAO,5,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1418692,2017,SP,3552809,***56821812**,1,4,1997-12-11,0,17854,NaN,NaN,PEDAGOGIA,1,1,1
1418693,2017,SP,3515004,***86830883**,1,2,1993-05-17,0,17854,NaN,NaN,PEDAGOGIA,3,1,1
1418694,2017,SP,3515004,***67219881**,1,2,1999-08-26,0,17854,NaN,NaN,ADMINISTRACAO,3,1,1
1418695,2017,SP,3552809,***31303827**,2,2,1999-01-24,0,17854,NaN,NaN,ENGENHARIA CIVIL,1,1,1
1418696,2017,SP,3525904,***98455655**,1,4,1999-03-16,0,17902,NaN,NaN,ADMINISTRACAO,3,2,1

***

In [4]:
analise_campos_vazio = dados_prouni.isna().sum()

analise_campos_vazio

ano                              0
sigla_uf                         0
id_municipio                  3651
cpf                              0
sexo                             0
raca_cor                         0
data_nascimento                  0
beneficiario_deficiente          0
id_ies                           0
campus                     1418697
nome_municipio_ies         1418697
curso                          307
turno_curso                      0
tipo_bolsa                       0
modalidade_ensino                0
dtype: int64